# Generated by Django 3.0.6 on 2020-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_and_translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersavedmodel',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='savedmodel',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
